#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Deze code is gegenereerd met een hulpprogramma.
//     Runtime-versie:4.0.30319.42000
//
//     Als u wijzigingen aanbrengt in dit bestand, kan dit onjuist gedrag veroorzaken wanneer
//     de code wordt gegenereerd.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AmnestyInternational.Resource", IsApplication=true)]

namespace AmnestyInternational
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int sample1 = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060008
			public const int VoornaamNaam = 2131099656;
			
			// aapt resource value: 0x7f060012
			public const int autoCompleteTextView1 = 2131099666;
			
			// aapt resource value: 0x7f060007
			public const int backToMain = 2131099655;
			
			// aapt resource value: 0x7f060014
			public const int button2 = 2131099668;
			
			// aapt resource value: 0x7f060003
			public const int checkedTextView2 = 2131099651;
			
			// aapt resource value: 0x7f060016
			public const int demoImageView = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int donate = 2131099671;
			
			// aapt resource value: 0x7f060004
			public const int editText1 = 2131099652;
			
			// aapt resource value: 0x7f06000a
			public const int editText2 = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int editText3 = 2131099660;
			
			// aapt resource value: 0x7f06000e
			public const int editText4 = 2131099662;
			
			// aapt resource value: 0x7f060010
			public const int editText5 = 2131099664;
			
			// aapt resource value: 0x7f060013
			public const int goToBedrag = 2131099667;
			
			// aapt resource value: 0x7f060015
			public const int linearLayout1 = 2131099669;
			
			// aapt resource value: 0x7f060001
			public const int naamId = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int textView1 = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int textView2 = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int textView3 = 2131099653;
			
			// aapt resource value: 0x7f060009
			public const int textView4 = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int textView5 = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int textView6 = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int textView7 = 2131099663;
			
			// aapt resource value: 0x7f060011
			public const int textView8 = 2131099665;
			
			// aapt resource value: 0x7f060006
			public const int toggleButton1 = 2131099654;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Bedrag = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Contactgegevens = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Main = 2130968578;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
